# Generated by Django 2.2.4 on 2020-01-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='prod',
        ),
        migrations.AddField(
            model_name='mycart',
            name='prod',
            field=models.ManyToManyField(null=True, to='products.Products'),
        ),
    ]
