# Generated by Django 2.2.4 on 2020-01-26 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200126_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='user',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
