# Generated by Django 2.2.4 on 2020-01-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_remove_mycart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
