# Generated by Django 2.2.4 on 2020-01-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_mycart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
