# Generated by Django 2.2.4 on 2020-02-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_quantity'),
        ('carts', '0008_auto_20200131_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='quantity',
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('subtotal', models.FloatField(null=True)),
                ('prod', models.ManyToManyField(null=True, to='products.Products')),
            ],
        ),
    ]
