# Generated by Django 2.2.4 on 2020-02-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20200209_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='carts.CartItems'),
        ),
    ]
