# Generated by Django 2.2.4 on 2020-02-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_auto_20200209_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='total',
        ),
        migrations.AddField(
            model_name='mycart',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
