# Generated by Django 2.2.4 on 2020-02-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_auto_20200209_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='items',
        ),
        migrations.AddField(
            model_name='mycart',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='carts.CartItems'),
        ),
    ]
