# Generated by Django 2.2.4 on 2020-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_auto_20200209_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='items',
        ),
        migrations.AddField(
            model_name='mycart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='carts.CartItems'),
        ),
    ]
