# Generated by Django 2.2.4 on 2020-02-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_quantity'),
        ('carts', '0014_auto_20200209_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='prod',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='prod',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='products.Products'),
        ),
    ]
