# Generated by Django 2.2.4 on 2020-02-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_auto_20200209_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='items',
            field=models.ManyToManyField(null=True, to='carts.CartItems'),
        ),
    ]
