# Generated by Django 2.2.4 on 2020-02-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0018_auto_20200209_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='items',
            field=models.ManyToManyField(to='carts.CartItems'),
        ),
    ]
