# Generated by Django 2.2.4 on 2020-02-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_quantity'),
        ('carts', '0022_auto_20200210_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='prod',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='prod',
            field=models.ForeignKey(default=0, on_delete='CASCADE', to='products.Products'),
            preserve_default=False,
        ),
    ]
