# Generated by Django 2.2.4 on 2020-02-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0023_auto_20200210_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='prod',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='products.Products'),
        ),
    ]
