# Generated by Django 2.2.4 on 2020-02-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0025_auto_20200210_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='subtotal',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='total',
        ),
    ]
