# Generated by Django 2.2.4 on 2020-02-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0026_auto_20200210_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='total',
        ),
    ]
