# Generated by Django 2.2.4 on 2020-02-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0028_cartitems_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mycart',
            name='subtotal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
