# Generated by Django 2.2.4 on 2020-02-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0029_auto_20200210_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mycart',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
    ]
