# Generated by Django 2.2.4 on 2020-01-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('P', 'Pakistan'), ('T', 'Turkey'), ('D', 'Dubai'), ('NZ', 'New Zealand'), ('U', 'USA'), ('A', 'Australia')], max_length=100, null=True),
        ),
    ]
