# Generated by Django 2.2.4 on 2020-01-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200131_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('D', 'Dubai'), ('U', 'USA'), ('P', 'Pakistan'), ('NZ', 'New Zealand'), ('A', 'Australia'), ('T', 'Turkey')], max_length=100, null=True),
        ),
    ]
