# Generated by Django 2.2.4 on 2020-01-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200131_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('T', 'Turkey'), ('U', 'USA'), ('A', 'Australia'), ('P', 'Pakistan'), ('NZ', 'New Zealand'), ('D', 'Dubai')], max_length=100, null=True),
        ),
    ]
