# Generated by Django 2.2.4 on 2020-02-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200209_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('A', 'Australia'), ('T', 'Turkey'), ('NZ', 'New Zealand'), ('P', 'Pakistan'), ('U', 'USA'), ('D', 'Dubai')], max_length=100, null=True),
        ),
    ]
