# Generated by Django 2.2.4 on 2020-02-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200209_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('P', 'Pakistan'), ('NZ', 'New Zealand'), ('T', 'Turkey'), ('A', 'Australia'), ('D', 'Dubai'), ('U', 'USA')], max_length=100, null=True),
        ),
    ]
