# Generated by Django 2.2.4 on 2020-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200209_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('P', 'Pakistan'), ('A', 'Australia'), ('U', 'USA'), ('D', 'Dubai'), ('NZ', 'New Zealand'), ('T', 'Turkey')], max_length=100, null=True),
        ),
    ]
