# Generated by Django 2.2.4 on 2020-02-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200209_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('U', 'USA'), ('NZ', 'New Zealand'), ('D', 'Dubai'), ('A', 'Australia'), ('P', 'Pakistan'), ('T', 'Turkey')], max_length=100, null=True),
        ),
    ]
