# Generated by Django 2.2.4 on 2020-02-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200209_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('P', 'Pakistan'), ('U', 'USA'), ('T', 'Turkey'), ('NZ', 'New Zealand'), ('D', 'Dubai'), ('A', 'Australia')], max_length=100, null=True),
        ),
    ]
