# Generated by Django 2.2.4 on 2020-02-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200210_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('P', 'Pakistan'), ('A', 'Australia'), ('D', 'Dubai'), ('U', 'USA'), ('T', 'Turkey'), ('NZ', 'New Zealand')], max_length=100, null=True),
        ),
    ]
