# Generated by Django 2.2.4 on 2020-02-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200210_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('U', 'USA'), ('D', 'Dubai'), ('A', 'Australia'), ('T', 'Turkey'), ('P', 'Pakistan'), ('NZ', 'New Zealand')], max_length=100, null=True),
        ),
    ]
