# Generated by Django 2.2.4 on 2020-02-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20200210_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('A', 'Australia'), ('U', 'USA'), ('NZ', 'New Zealand'), ('T', 'Turkey'), ('D', 'Dubai'), ('P', 'Pakistan')], max_length=100, null=True),
        ),
    ]
