# Generated by Django 2.2.4 on 2020-02-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200210_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('P', 'Pakistan'), ('NZ', 'New Zealand'), ('T', 'Turkey'), ('D', 'Dubai'), ('U', 'USA'), ('A', 'Australia')], max_length=100, null=True),
        ),
    ]
