# Generated by Django 2.2.4 on 2020-02-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20200210_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('D', 'Dubai'), ('U', 'USA'), ('P', 'Pakistan'), ('A', 'Australia'), ('T', 'Turkey'), ('NZ', 'New Zealand')], max_length=100, null=True),
        ),
    ]
