# Generated by Django 2.2.4 on 2020-02-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200210_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('A', 'Australia'), ('NZ', 'New Zealand'), ('P', 'Pakistan'), ('T', 'Turkey'), ('D', 'Dubai'), ('U', 'USA')], max_length=100, null=True),
        ),
    ]
