# Generated by Django 2.2.4 on 2020-02-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200210_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('NZ', 'New Zealand'), ('T', 'Turkey'), ('U', 'USA'), ('P', 'Pakistan'), ('A', 'Australia'), ('D', 'Dubai')], max_length=100, null=True),
        ),
    ]
