# Generated by Django 2.2.4 on 2020-02-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20200210_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('U', 'USA'), ('T', 'Turkey'), ('P', 'Pakistan'), ('A', 'Australia'), ('D', 'Dubai'), ('NZ', 'New Zealand')], max_length=100, null=True),
        ),
    ]
