# Generated by Django 2.2.4 on 2020-02-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20200213_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('NZ', 'New Zealand'), ('D', 'Dubai'), ('P', 'Pakistan'), ('A', 'Australia'), ('T', 'Turkey'), ('U', 'USA')], max_length=100, null=True),
        ),
    ]
