# Generated by Django 2.2.4 on 2020-02-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20200213_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('NZ', 'New Zealand'), ('D', 'Dubai'), ('U', 'USA'), ('A', 'Australia'), ('T', 'Turkey'), ('P', 'Pakistan')], max_length=100, null=True),
        ),
    ]
