# Generated by Django 2.2.4 on 2020-02-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20200214_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('U', 'USA'), ('NZ', 'New Zealand'), ('P', 'Pakistan'), ('D', 'Dubai'), ('T', 'Turkey'), ('A', 'Australia')], max_length=100, null=True),
        ),
    ]
