# Generated by Django 2.2.4 on 2020-02-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20200214_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('NZ', 'New Zealand'), ('D', 'Dubai'), ('U', 'USA'), ('T', 'Turkey'), ('P', 'Pakistan'), ('A', 'Australia')], max_length=100, null=True),
        ),
    ]
