# Generated by Django 2.2 on 2020-04-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20200405_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('A', 'Australia'), ('NZ', 'New Zealand'), ('U', 'USA'), ('T', 'Turkey'), ('D', 'Dubai'), ('P', 'Pakistan')], max_length=100, null=True),
        ),
    ]
