# Generated by Django 2.2.4 on 2020-01-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='static')),
                ('descriptions', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
